# SysMetrics — system diagnostics for Sailfish OS.

TARGET = harbour-sysmetrics

CONFIG += sailfishapp sailfishapp_i18n c++17

QT += dbus network

# Version reaches the build as DEFINES+=SYSMETRICS_VERSION=... from the spec.
SYSMETRICS_VERSION_VALUE = dev
for(def, DEFINES) {
    contains(def, "SYSMETRICS_VERSION=.*") {
        SYSMETRICS_VERSION_VALUE = $$replace(def, "SYSMETRICS_VERSION=", "")
    }
}
VERSION_HEADER_LINES = \
    "// Generated by qmake — do not edit." \
    "$${LITERAL_HASH}define SYSMETRICS_VERSION_STRING \"$$SYSMETRICS_VERSION_VALUE\""
!write_file($$PWD/src/generated/sysmetrics_version.h, VERSION_HEADER_LINES) {
    error("could not write src/generated/sysmetrics_version.h")
}
INCLUDEPATH += src/generated

HEADERS += \
    src/sampler.h \
    src/sysmon.h \
    src/procmodel.h \
    src/netinfo.h \
    src/deviceinfo.h \
    src/detailmon.h \
    src/btinfo.h \
    src/netmon.h \
    src/recorder.h \
    src/graphitem.h \
    src/rootclient.h \
    src/roothelper.h

SOURCES += \
    src/harbour-sysmetrics.cpp \
    src/sampler.cpp \
    src/sysmon.cpp \
    src/procmodel.cpp \
    src/netinfo.cpp \
    src/deviceinfo.cpp \
    src/detailmon.cpp \
    src/btinfo.cpp \
    src/netmon.cpp \
    src/recorder.cpp \
    src/graphitem.cpp \
    src/rootclient.cpp \
    src/roothelper.cpp

SAILFISHAPP_ICONS = 86x86 108x108 128x128 172x172

# Optional privileged helper as a system service (installed, not enabled).
helperservice.files = data/harbour-sysmetrics-helper.service
helperservice.path = /usr/lib/systemd/system
INSTALLS += helperservice

TRANSLATIONS += translations/harbour-sysmetrics-de.ts
lupdate_only {
    SOURCES += qml/*.qml qml/cover/*.qml qml/pages/*.qml qml/components/*.qml
}

DISTFILES += \
    README.md \
    harbour-sysmetrics.desktop \
    rpm/harbour-sysmetrics.spec \
    qml/harbour-sysmetrics.qml \
    qml/cover/CoverPage.qml \
    qml/components/qmldir \
    qml/components/Diag.qml \
    qml/components/DiagBackground.qml \
    qml/components/MetricCard.qml \
    qml/components/LoadBar.qml \
    qml/components/FilterPill.qml \
    qml/components/KeyValue.qml \
    qml/components/MoreToggle.qml \
    qml/pages/MainPage.qml \
    qml/pages/ConnectionsPage.qml \
    qml/pages/ConnectionDetailPage.qml \
    qml/pages/OverviewPage.qml \
    qml/pages/ProcessDetailPage.qml \
    qml/pages/RecordPage.qml \
    qml/pages/SettingsPage.qml \
    qml/pages/AboutPage.qml \
    qml/pages/HelpPage.qml \
    qml/pages/InfoDetailPage.qml \
    qml/pages/HwInfo.js \
    qml/pages/SensorsPage.qml \
    qml/pages/SensorContent.qml
